### ISSUE TITLE
Does this support null safety?

### ISSUE THREAD

**Issue by talamaska** [simolus3/analyzer_plugin_fork#1]

**Comment by simolus3** [comment]
You should probably use the regular `analyzer_plugin` package (which does support null safety now). I'm only using this in moor because the `analyzer_plugin` package is updated very infrequently.

**Comment by talamaska** [comment]
right I'm using moor as well, and I saw this depenedency as transitive dev_dependency and was wondering if I just update moor, will it be null-safe

**Comment by simolus3** [comment]
This is a transitive dependency of `moor_generator` which you don't import in your app. You can safely migrate your app to null-safety without `analyzer_plugin_fork` (or things like `build_runner`) being migrated.

**Comment by talamaska** [comment]
thanks
